cart/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<product_id>/', views.cart_remove, name='cart_remove'),
]

internet_shop/urls.py
from django.urls import re_path, path
from . import views

"""
urlpatterns = [
    re_path(r'^$', views.ProductList.as_view(), name='product_list'),
    re_path(r'^(?P<category_slug>[-\w]+)/$', views.ProductList.as_view(), name='product_list_by_category'),
    re_path(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.ProductDetail.as_view(), name='product_detail'),
]
"""

urlpatterns = [
    path('', views.ProductList.as_view(), name='product_list'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('<slug:category_slug>/', views.ProductList.as_view(), name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.ProductDetail.as_view(), name='product_detail'),
]

# https://gist.github.com/jduff/567195/eeaab1d5cfcbc033c947ae9c4744fec4e16c0809 'base.css'

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
    path('', include(('internet_shop.urls', 'internet_shop'), namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

internet_shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категорія'
        verbose_name_plural = 'Категорії'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                       args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING, related_name='products')
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='images/products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)
        verbose_name = 'Товар'
        verbose_name_plural = 'Товари'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                       args=[self.id, self.slug])


class Comment(models.Model):
    product = models.ForeignKey(Product, related_name='comments', on_delete=models.CASCADE)
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

internet_shop/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import Comment


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='User name', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='User name', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-input'}))


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

internet_shop/views.py
from django.contrib.auth import logout, login
from django.contrib.auth.views import LoginView
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView, CreateView
from django.urls import reverse_lazy

from .forms import RegisterUserForm, LoginUserForm, CommentForm
from .models import Product, Category
from .utils import DataMixin

from cart.forms import CartAddProductForm


class ProductList(DataMixin, ListView):
    model = Product
    context_object_name = 'products'

    def get_queryset(self):
        category_slug = self.kwargs.get('category_slug')
        products = Product.objects.filter(available=True)
        if category_slug:
            category = get_object_or_404(Category, slug=category_slug)
            products = products.filter(category=category)
        return products

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)

        category = None
        category_slug = self.kwargs.get('category_slug')
        if category_slug:
            category = get_object_or_404(Category, slug=category_slug)
        if category:
            cat_selected = category.pk
            title = 'Category - ' + str(category.name)
        else:
            cat_selected = 0
            title = 'All products'

        c_def = self.get_user_context(title=title, cat_selected=cat_selected)

        return dict(list(context.items()) + list(c_def.items()))


class ProductDetail(DataMixin, DetailView):
    model = Product

    def post(self, request, **kwargs):
        comment_form = CommentForm(data=request.POST)
        product = get_object_or_404(Product, id=kwargs['id'],
                                    slug=kwargs['slug'],)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.product = product
            new_comment.save()

        return redirect(product.get_absolute_url())

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            comment_form = CommentForm(data=self.request.POST)
        else:
            comment_form = CommentForm()

        c_def = self.get_user_context(cart_product_form=CartAddProductForm(),
                                      comments=self.object.comments.filter(active=True),
                                      comment_form=comment_form,)

        return dict(list(context.items()) + list(c_def.items()))


class RegisterUser(DataMixin, CreateView):
    form_class = RegisterUserForm
    template_name = 'internet_shop/register.html'
    success_url = reverse_lazy('shop:login')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Registration")

        return dict(list(context.items()) + list(c_def.items()))

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('shop:product_list')


class LoginUser(DataMixin, LoginView):
    form_class = LoginUserForm
    template_name = 'internet_shop/login.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Login")
        return dict(list(context.items()) + list(c_def.items()))

    def get_success_url(self):
        return reverse_lazy('shop:product_list')


def logout_user(request):
    logout(request)
    return redirect('shop:login')


# def product_detail(request, id, slug):
#     product = get_object_or_404(Product,
#                                 id=id,
#                                 slug=slug,
#                                 available=True)
#     cart_product_form = CartAddProductForm()
#     return render(request, 'internet_shop/product_detail.html', {'product': product,
#                                                         'cart_product_form': cart_product_form})

internet_shop/templates/internet_shop/about.html
{% extends "internet_shop/base.html" %}

{% block content %}
<h1>{{title}}</h1>

{% endblock %}

internet_shop/templates/internet_shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}My shop{% endblock %}</title>
    <link href="{% static 'internet_shop/css/mystyle.css' %}" rel="stylesheet">
</head>
<body>
<div class="topnav">
    <ul>
        <li><a class="active" href="{% url 'shop:product_list' %}">My shop</a></li>
        <li><a href="#about">About</a></li>

        <div class="topnav-right">
        {% if request.user.is_authenticated %}
            <li class="last"><a href="{% url 'cart:cart_detail' %}">Cart</a></li>
            <li class="last">{{user.username}}|<a href="{% url 'shop:logout' %}">Logout</a> </li>
        {% else %}
            <li class="last"><a href="{% url 'shop:register' %}">Registration</a>|<a href="{% url 'shop:login' %}">Login</a></li>
        {% endif %}
        </div>
    </ul>
</div>
<div class="content-input">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

internet_shop/templates/internet_shop/login.html
{% extends 'internet_shop/base.html' %}

{% block content %}
    <h1>{{title}}</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
{% endblock %}

internet_shop/templates/internet_shop/product_detail.html
{% extends "internet_shop/base.html" %}
{% load static %}

{% block title %}
    {{ product }}
{% endblock %}

{% block content %}
    <div class="item-detail">
        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
        <h1>{{ product.name }}</h1>
        <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
        <p class="price">₴{{ product.price }}</p>

        {% if request.user.is_authenticated %}
        <form action="{% url 'cart:cart_add' product.id %}" method="post">
            {{ cart_product_form }}
            {% csrf_token %}
        <input type="submit" value="Add to cart">
        </form>
        {% endif %}

        {{ product.description|linebreaks }}

        {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }} comment{{ total_comments|pluralize }}
        </h2>
        {% endwith %}

        {% for comment in comments %}
            <div class="comment">
                <p class="info">
                    Comment {{ forloop.counter }} by {{ comment.name }}
                    {{ comment.created }}
                </p>
                {{ comment.body|linebreaks }}
            </div>
        {% empty %}
            <p>There are no comments yet.</p>
        {% endfor %}

        {% if request.user.is_authenticated %}
        {% if new_comment %}
            <h2>Your comment has been added.</h2>
        {% else %}
            <h2>Add a new comment</h2>
            <form action="." method="post">
                {{ comment_form.as_p }}
                {% csrf_token %}
            <p><input type="submit" value="Add comment"></p>
            </form>
        {% endif %}
        {% endif %}
    </div>
{% endblock %}

internet_shop/templates/internet_shop/product_list.html
{% extends "internet_shop/base.html" %}
{% load static %}
{% block title %}
    {{title}}
{% endblock %}
{% block content %}
    <div class="sidenav">
        <h3>Categories</h3>
        <ul>
            <li {% if not cat_selected %}class="selected"{% endif %}>
                <a href="{% url 'shop:product_list' %}">All</a>
            </li>
            {% for c in categories %}
                <li {% if cat_selected == c.pk %}class="selected"{% endif %}>
                    <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div class="main">
        <h1>{{ title }}</h1>
        {% for product in products %}
            <div class="item">
                <a href="{{ product.get_absolute_url }}">
                    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
                </a>
                <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
                ₴{{ product.price }}
            </div>
        {% endfor %}
    </div>
{% endblock %}

internet_shop/templates/internet_shop/register.html
{% extends 'internet_shop/base.html' %}

{% block content %}
    <h1>{{ title }}</h1>

    <form method="post">
        {% csrf_token %}
        {% for field in form %}
            <p><label class="form-label" for="{{ field.id_for_label }}">{{field.label}}</label> {{ field }}</p>
            <div class="form-error"> {{ field.errors }}</div>
        {% endfor %}
        <button type="submit">Registration</button>
    </form>

{% endblock %}